-- LABORATORIES table: Stores details of each lab
CREATE TABLE LABORATORIES (
    LAB_ID INT AUTO_INCREMENT PRIMARY KEY,
    LAB_NAME VARCHAR(100) NOT NULL,
    TOTAL_COMPUTERS INT NOT NULL DEFAULT 50
);

-- COMPUTERS table: Tracks each computer in a lab
CREATE TABLE COMPUTERS (
    COMPUTER_ID INT AUTO_INCREMENT PRIMARY KEY,
    LAB_ID INT NOT NULL,
    STATUS ENUM('AVAILABLE', 'OCCUPIED') NOT NULL DEFAULT 'AVAILABLE',
    FOREIGN KEY (LAB_ID) REFERENCES LABORATORIES(LAB_ID) ON DELETE CASCADE
);

-- SCHEDULES table: Stores class schedules
CREATE TABLE SCHEDULES (
    SCHEDULE_ID INT AUTO_INCREMENT PRIMARY KEY,
    LAB_ID INT NOT NULL,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    DAY ENUM('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT') NOT NULL,
    FOREIGN KEY (LAB_ID) REFERENCES LABORATORIES(LAB_ID) ON DELETE CASCADE
);

-- SIT_IN_RECORDS table: Stores sit-in requests by students
CREATE TABLE SIT_IN_RECORDS (
    RECORD_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_IDNO VARCHAR(50) NOT NULL,  -- Reference to USERS.IDNO
    LAB_ID INT NOT NULL,
    COMPUTER_ID INT NOT NULL,
    DATE DATE NOT NULL,
    STATUS ENUM('PENDING', 'APPROVED', 'DENIED') NOT NULL DEFAULT 'PENDING',
    FOREIGN KEY (USER_IDNO) REFERENCES USERS(IDNO) ON DELETE CASCADE,
    FOREIGN KEY (LAB_ID) REFERENCES LABORATORIES(LAB_ID) ON DELETE CASCADE,
    FOREIGN KEY (COMPUTER_ID) REFERENCES COMPUTERS(COMPUTER_ID) ON DELETE CASCADE
);

-- SIT_IN_LIMITS table: Tracks the number of sit-ins per student (Max 30)
CREATE TABLE SIT_IN_LIMITS (
    USER_IDNO VARCHAR(50) PRIMARY KEY,  -- Reference to USERS.IDNO
    SIT_IN_COUNT INT NOT NULL DEFAULT 0,
    FOREIGN KEY (USER_IDNO) REFERENCES USERS(IDNO) ON DELETE CASCADE
);
