-- Table for student rewards
CREATE TABLE IF NOT EXISTS STUDENT_REWARDS (
    REWARD_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID VARCHAR(20) NOT NULL,
    REWARD_TYPE VARCHAR(50) NOT NULL,
    POINTS_EARNED INT NOT NULL,
    DATE_EARNED DATETIME NOT NULL,
    DESCRIPTION TEXT,
    FOREIGN KEY (STUDENT_ID) REFERENCES USERS(IDNO)
);

-- Table for lab schedule
CREATE TABLE IF NOT EXISTS LAB_SCHEDULE (
    SCHEDULE_ID INT AUTO_INCREMENT PRIMARY KEY,
    LAB_ID INT NOT NULL,
    DAY_OF_WEEK VARCHAR(10) NOT NULL,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    SUBJECT VARCHAR(100) NOT NULL,
    INSTRUCTOR VARCHAR(100) NOT NULL,
    FOREIGN KEY (LAB_ID) REFERENCES LABORATORIES(LAB_ID)
); 